---

- name: Generate Service's template
  template:
    src: icingaCore.service.j2
    dest: /etc/systemd/system/icingaCore.service
    
- name: Generate Compose's template
  template:
    src: docker-compose.j2
    dest: "{{ docker_folder }}/core/docker-compose.yml"

- name: restart icinga-core service
  systemd:
    state: restarted
    daemon_reload: yes
    name: icingaCore

