---

- name: Generate Service's template
  template:
    src: icingaBBDD.service.j2
    dest: /etc/systemd/system/icingaBBDD.service

- name: Generate Service's template
  template:
    src: docker-compose.j2
    dest: "{{ docker_folder }}/bbdd/docker-compose.yml"
    
- name: restart icinga-bbdd service
  systemd:
    state: restarted
    daemon_reload: yes
    name: icingaBBDD